# Setup dependabot updates

version: 2

updates:

  # Update GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"

  # Update Poetry dependencies
  - package-ecosystem: "pip"  # yes, this is correct
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
