name: Release

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  release:
    uses: MrThearMan/CI/.github/workflows/release.yml@v0.4.1
    secrets:
      pypi-token: ${{ secrets.PYPI_API_TOKEN }}
